databases:
  - name: accounting-api-posgre
    databaseName: accounting-api-posgre
    user: accounting-api
    region: singapore

services:
  - type: web
    name: accounting-api-posgre
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: accounting-api-posgre
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false