databases:
  - name: posgre
    databaseName: posgre
    user: ekoki
    region: singapore

services:
  - type: web
    name: posgre
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: posgre
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false