databases:
  - name: dpg-cjpb3h8jbais73864r50-a
    databaseName: dpg-cjpb3h8jbais73864r50-a
    user: ekoki
    region: singapore

services:
  - type: web
    name: accounting-api-posgre
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: dpg-cjpb3h8jbais73864r50-a
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false